### ISSUE TITLE
I get an error when  I run example in RStudio?

### ISSUE THREAD

**Issue by rvitancol** [mexchy1000/spade#1]
Hi. Thank you for writing this. 

I am interested to use this for my data and see what information it will give me when I combine image with the counts. Can I run this in Rstudio? I tried to run  the example but it is giving me the below error. Thank you in advance for your reply.

> use_condaenv(condaenv = 'Tf', required = TRUE)  # Appropriate System Environment to run tensorflow/keras
Error in use_condaenv(condaenv = "Tf", required = TRUE) : 
  Unable to locate conda environment 'Tf'.

**Comment by dirolamo** [comment]
try change 'Tf' to your locate conda environment.

**Comment by hehuifeng** [comment]
> 

try change 'Tf' to your locate conda environment.

**Comment by rvitancol** [comment]
Thanks I was able to make this work.
